name: Tests

on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"
      - "v*.*.*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: pin python version
        run: uv python pin 3.13
      - name: Install tox-uv
        run: uv tool install tox --with tox-uv
      - name: Run tests
        run: tox
